erDiagram
    USER {
        _id ObjectId PK
        name string
        email string
        phoneNumber string
        address object
        role string
        isRegistered boolean
        password string
        createdAt date
        updatedAt date
        profileImage string
    }

    %% `
    
    CATEGORY {
        _id ObjectId PK
        name string
        description string
        fields array
        createdBy ObjectId FK
    }

    ROLE {
        _id ObjectId PK
        name string
        description string
        createdBy ObjectId FK
    }

    PERMISSION {
        _id ObjectId PK
        name string
        description string
        createdBy ObjectId FK
    }
    
    %% FIELD_DEFINITION {
    %%     name string
    %%     type string
    %%     required boolean
    %% }
    
    PRODUCT {
        _id ObjectId PK
        name string
        description string
        price number
        category ObjectId FK
        fieldValues array
        createdBy ObjectId FK
        createdAt date
        updatedAt date
        quantity number
    }
    
    %% PRODUCT_FIELD_VALUE {
    %%     name string
    %%     value mixed
    %% }
    
    CART {
        _id ObjectId PK
        %% items array
        user ObjectId FK
        createdAt date
        updatedAt date
    }
    
    CART_ITEM {
        product ObjectId FK
        quantity number
    }
    
    ORDER {
        _id ObjectId PK
        items array
        user ObjectId FK
        status string
        shippingAddress object
        paymentDetails object
        totalAmount number
        createdAt date
        updatedAt date
    }
    
    ORDER_ITEM {
        product ObjectId FK
        quantity number
        voucher string
        note string
        unitPrice number
        deliveryDate date
        deliveryFee number
    }
    
    %% STORAGE {
    %%     _id ObjectId PK
    %%     items array
    %%     createdAt date
    %%     updatedAt date
    %% }
    
    %% STORAGE_ITEM {
    %%     product ObjectId FK
    %%     quantity number
    %%     createdAt date
    %%     updatedAt date
    %% }

    VOUCHER {
        _id ObjectId PK
        name string
        description string
        discount number
        startDate date
        endDate date
        createdBy ObjectId FK
    }
    
    PAYMENT_HISTORY {
        _id ObjectId PK
        order ObjectId FK
        user ObjectId FK
        amount number
        paymentMethod string
        status string
        transactionId string
        gatewayResponse string
        isRefund boolean
        refundedPayment ObjectId FK
        paymentDate date
        createdAt date
        updatedAt date
    }

    
    USER ||--o{ ORDER : "places"
    USER ||--o{ CART : "has"
    USER ||--|| ROLE : "has"
    USER ||--o{ PERMISSION : "granted"
    USER ||--o{ PAYMENT_HISTORY : "makes"
    CATEGORY ||--o{ PRODUCT : "categorizes"
    PAYMENT_HISTORY ||--o{ PAYMENT_HISTORY : "refunds"
    
    PRODUCT ||--o{ CART_ITEM : "referenced in"
    PRODUCT ||--o{ ORDER_ITEM : "referenced in"
    
    CART ||--o{ CART_ITEM : "contains"
    
    ORDER ||--o{ ORDER_ITEM : "contains"
    ORDER ||--o{ PAYMENT_HISTORY : "has"
    
    VOUCHER ||--o{ ORDER_ITEM : "applies to"
    VOUCHER ||--o{ USER : "granted to"
    VOUCHER ||--o{ PRODUCT : "applies to"
    
